In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [2]:
df = pd.read_csv("FINAL_PBL_DATA_SET_7.csv" )

In [3]:
df.head()

,CUSTOMER_ID,INVOICE_NO,STOCK_CODE,QUANTITY,INVOICE_DATE,UNIT_PRICE,PRODUCT_CATEGORY,ITEM_RETURNED,NO_OF_ITEMS_RETURNED
0,17850.0,536365,84029G,2,2010-12-01 08:26:00,220.35,Others,NO,0
1,17850.0,536365,84029E,1,2010-12-01 08:26:00,220.35,Others,NO,0
2,17850.0,536365,22752,1,2010-12-01 08:26:00,497.25,Others,NO,0
3,17850.0,536366,22633,4,2010-12-01 08:28:00,120.25,Others,NO,0
4,17850.0,536366,22632,2,2010-12-01 08:28:00,120.25,Others,NO,0

In [4]:
df["SPENDING"] = df["QUANTITY"]*df["UNIT_PRICE"]

In [5]:
df["Returned_Amount"] = df["UNIT_PRICE"]*df["NO_OF_ITEMS_RETURNED"]

In [6]:
df.head()

,CUSTOMER_ID,INVOICE_NO,STOCK_CODE,QUANTITY,INVOICE_DATE,UNIT_PRICE,PRODUCT_CATEGORY,ITEM_RETURNED,NO_OF_ITEMS_RETURNED,SPENDING,Returned_Amount
0,17850.0,536365,84029G,2,2010-12-01 08:26:00,220.35,Others,NO,0,440.70,0.0
1,17850.0,536365,84029E,1,2010-12-01 08:26:00,220.35,Others,NO,0,220.35,0.0
2,17850.0,536365,22752,1,2010-12-01 08:26:00,497.25,Others,NO,0,497.25,0.0
3,17850.0,536366,22633,4,2010-12-01 08:28:00,120.25,Others,NO,0,481.00,0.0
4,17850.0,536366,22632,2,2010-12-01 08:28:00,120.25,Others,NO,0,240.50,0.0

In [7]:
df["CUSTOMER_ID"].nunique()

3910

In [8]:
df_1 = df.groupby("CUSTOMER_ID")["SPENDING"].sum()

In [9]:
df1 = pd.DataFrame(df_1)

In [44]:
df1.head()

               SPENDING
CUSTOMER_ID
12747.0        50694.15
12748.0      1514026.80
12749.0       146544.45
12820.0        11971.70
12821.0         1374.10

In [11]:
df_2 = df.groupby("CUSTOMER_ID")["INVOICE_NO"].nunique()

In [12]:
df["TotalPrice"] = df["QUANTITY"] * df["UNIT_PRICE"]

In [13]:
df.head()

,CUSTOMER_ID,INVOICE_NO,STOCK_CODE,QUANTITY,INVOICE_DATE,UNIT_PRICE,PRODUCT_CATEGORY,ITEM_RETURNED,NO_OF_ITEMS_RETURNED,SPENDING,Returned_Amount,TotalPrice
0,17850.0,536365,84029G,2,2010-12-01 08:26:00,220.35,Others,NO,0,440.70,0.0,440.70
1,17850.0,536365,84029E,1,2010-12-01 08:26:00,220.35,Others,NO,0,220.35,0.0,220.35
2,17850.0,536365,22752,1,2010-12-01 08:26:00,497.25,Others,NO,0,497.25,0.0,497.25
3,17850.0,536366,22633,4,2010-12-01 08:28:00,120.25,Others,NO,0,481.00,0.0,481.00
4,17850.0,536366,22632,2,2010-12-01 08:28:00,120.25,Others,NO,0,240.50,0.0,240.50

In [14]:
df_3 = df.groupby("CUSTOMER_ID").agg({
    'SPENDING': 'sum',
    'INVOICE_NO': 'nunique',
    'QUANTITY': 'sum'
}).rename(columns={
    'TOTAL_PRICE': 'Total_Spending',
    'INVOICE_NO': 'FREQUENCY',
    'QUANTITY': 'TOTAL_QUANTITY'
}).reset_index()

In [43]:
df_3.head()

   CUSTOMER_ID    SPENDING  FREQUENCY  TOTAL_QUANTITY
0      12747.0    50694.15         11             191
1      12748.0  1514026.80        208            8221
2      12749.0   146544.45          7             401
3      12820.0    11971.70          4              83
4      12821.0     1374.10          1               4

In [16]:
df_4 = df.groupby('CUSTOMER_ID').agg({
    'QUANTITY': 'sum',
    'SPENDING': 'sum',
    'NO_OF_ITEMS_RETURNED': 'sum',
    "Returned_Amount" : 'sum'
}).reset_index()

In [42]:
df_4.head()

,CUSTOMER_ID,QUANTITY,SPENDING,NO_OF_ITEMS_RETURNED,Returned_Amount,Return_Ratio,Return_Amaount_Ratio
0,12747.0,191,50694.15,13,5082.35,0.068063,9.974549
1,12748.0,8221,1514026.80,534,92810.25,0.064956,16.313142
2,12749.0,401,146544.45,22,6607.25,0.054863,22.179341
3,12820.0,83,11971.70,6,952.25,0.072289,12.572014
4,12821.0,4,1374.10,0,0.00,0.000000,0.000000

In [18]:
df_4['Return_Ratio'] = (
    df_4['NO_OF_ITEMS_RETURNED'] /
    df_4['QUANTITY']
)

In [19]:
df_4['Return_Amaount_Ratio'] = (
    df_4['SPENDING'] /
    df_4['Returned_Amount']
)

In [21]:
df_4["Return_Amaount_Ratio"] = df_4["Return_Amaount_Ratio"].replace(float('inf'), 0)

In [46]:
df_4.head()

,CUSTOMER_ID,QUANTITY,SPENDING,NO_OF_ITEMS_RETURNED,Returned_Amount,Return_Ratio,Return_Amaount_Ratio
0,12747.0,191,50694.15,13,5082.35,0.068063,9.974549
1,12748.0,8221,1514026.80,534,92810.25,0.064956,16.313142
2,12749.0,401,146544.45,22,6607.25,0.054863,22.179341
3,12820.0,83,11971.70,6,952.25,0.072289,12.572014
4,12821.0,4,1374.10,0,0.00,0.000000,0.000000

In [47]:
df_5 = df.groupby('CUSTOMER_ID')['PRODUCT_CATEGORY'].apply(list).reset_index()

df_5.head()

   CUSTOMER_ID                                   PRODUCT_CATEGORY
0      12747.0  [Groceries, Others, Others, Others, Others, Ot...
1      12748.0  [Others, Others, Others, Groceries, Others, Ot...
2      12749.0  [Others, Others, Others, Others, Others, Other...
3      12820.0  [Others, Others, Others, Others, Others, Other...
4      12821.0                           [Others, Others, Others]

In [48]:
df_5 = df.groupby('CUSTOMER_ID')['PRODUCT_CATEGORY'] \
               .apply(lambda x: sorted(set(x))) \
               .reset_index()

df_5.head()

   CUSTOMER_ID                                   PRODUCT_CATEGORY
0      12747.0              [Groceries, Home Decor, Others, Toys]
1      12748.0  [Clothing, Groceries, Home Decor, Kitchenware,...
2      12749.0                   [Groceries, Kitchenware, Others]
3      12820.0                         [Home Decor, Others, Toys]
4      12821.0                                           [Others]

In [49]:
df_top2 = df.groupby('CUSTOMER_ID')['PRODUCT_CATEGORY'] \
    .apply(lambda x: x.value_counts().head(2).index.tolist()) \
    .reset_index()

df_top2.head()

   CUSTOMER_ID       PRODUCT_CATEGORY
0      12747.0   [Others, Home Decor]
1      12748.0  [Others, Kitchenware]
2      12749.0  [Others, Kitchenware]
3      12820.0         [Others, Toys]
4      12821.0               [Others]

In [50]:
merged_df = pd.merge(df_3, df_4, on='CUSTOMER_ID', how='inner')
merged_df.head()

,CUSTOMER_ID,SPENDING_x,FREQUENCY,TOTAL_QUANTITY,QUANTITY,SPENDING_y,NO_OF_ITEMS_RETURNED,Returned_Amount,Return_Ratio,Return_Amaount_Ratio
0,12747.0,50694.15,11,191,191,50694.15,13,5082.35,0.068063,9.974549
1,12748.0,1514026.80,208,8221,8221,1514026.80,534,92810.25,0.064956,16.313142
2,12749.0,146544.45,7,401,401,146544.45,22,6607.25,0.054863,22.179341
3,12820.0,11971.70,4,83,83,11971.70,6,952.25,0.072289,12.572014
4,12821.0,1374.10,1,4,4,1374.10,0,0.00,0.000000,0.000000

In [27]:
final_df = pd.merge(merged_df,df_top2,on='CUSTOMER_ID', how='inner')
final_df.head()

,CUSTOMER_ID,SPENDING_x,FREQUENCY,TOTAL_QUANTITY,QUANTITY,SPENDING_y,NO_OF_ITEMS_RETURNED,Returned_Amount,Return_Ratio,Return_Amaount_Ratio,PRODUCT_CATEGORY
0,12747.0,50694.15,11,191,191,50694.15,13,5082.35,0.068063,9.974549,"[Others, Home Decor]"
1,12748.0,1514026.80,208,8221,8221,1514026.80,534,92810.25,0.064956,16.313142,"[Others, Kitchenware]"
2,12749.0,146544.45,7,401,401,146544.45,22,6607.25,0.054863,22.179341,"[Others, Kitchenware]"
3,12820.0,11971.70,4,83,83,11971.70,6,952.25,0.072289,12.572014,"[Others, Toys]"
4,12821.0,1374.10,1,4,4,1374.10,0,0.00,0.000000,0.000000,[Others]
...,...,...,...,...,...,...,...,...,...,...,...
3905,18280.0,4774.25,1,20,20,4774.25,0,0.00,0.000000,0.000000,[Others]
3906,18281.0,2094.30,1,18,18,2094.30,0,0.00,0.000000,0.000000,[Others]
3907,18282.0,2579.20,3,13,13,2579.20,2,882.70,0.153846,2.921944,"[Others, Kitchenware]"
3908,18283.0,132707.90,15,1266,1266,132707.90,74,10791.95,0.058452,12.296934,"[Others, Groceries]"
3909,18287.0,11934.65,3,135,135,11934.65,21,1571.05,0.155556,7.596607,"[Others, Home Decor]"

In [28]:
type(final_df)

pandas.core.frame.DataFrame

In [29]:
final_df = final_df.drop('SPENDING_y', axis=1)
final_df = final_df.drop('QUANTITY', axis=1)

In [30]:
final_df.head()

,CUSTOMER_ID,SPENDING_x,FREQUENCY,TOTAL_QUANTITY,NO_OF_ITEMS_RETURNED,Returned_Amount,Return_Ratio,Return_Amaount_Ratio,PRODUCT_CATEGORY
0,12747.0,50694.15,11,191,13,5082.35,0.068063,9.974549,"[Others, Home Decor]"
1,12748.0,1514026.80,208,8221,534,92810.25,0.064956,16.313142,"[Others, Kitchenware]"
2,12749.0,146544.45,7,401,22,6607.25,0.054863,22.179341,"[Others, Kitchenware]"
3,12820.0,11971.70,4,83,6,952.25,0.072289,12.572014,"[Others, Toys]"
4,12821.0,1374.10,1,4,0,0.00,0.000000,0.000000,[Others]

In [31]:
final_df = final_df.rename(columns={'SPENDING_x': 'TOTAL_SPENDING', "Return_Amaount_Ratio": "RETURN_AMOUNT_RATIO" ,  "Return_Ratio":"RETURN_RATIO","Returned_Amount":"RETURNED_AMOUNT", "PRODUCT_CATEGORY" : "TOP_CATEGORY"})

In [32]:
print(type(final_df))

<class 'pandas.core.frame.DataFrame'>

In [33]:
final_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3910 entries, 0 to 3909
Data columns (total 9 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   CUSTOMER_ID           3910 non-null   float64
 1   TOTAL_SPENDING        3910 non-null   float64
 2   FREQUENCY             3910 non-null   int64
 3   TOTAL_QUANTITY        3910 non-null   int64
 4   NO_OF_ITEMS_RETURNED  3910 non-null   int64
 5   RETURNED_AMOUNT       3910 non-null   float64
 6   RETURN_RATIO          3910 non-null   float64
 7   RETURN_AMOUNT_RATIO   3910 non-null   float64
 8   TOP_CATEGORY          3910 non-null   object
dtypes: float64(5), int64(3), object(1)
memory usage: 275.1+ KB

In [34]:
type(final_df)

pandas.core.frame.DataFrame

In [35]:
final_df.head()

,CUSTOMER_ID,TOTAL_SPENDING,FREQUENCY,TOTAL_QUANTITY,NO_OF_ITEMS_RETURNED,RETURNED_AMOUNT,RETURN_RATIO,RETURN_AMOUNT_RATIO,TOP_CATEGORY
0,12747.0,50694.15,11,191,13,5082.35,0.068063,9.974549,"[Others, Home Decor]"
1,12748.0,1514026.80,208,8221,534,92810.25,0.064956,16.313142,"[Others, Kitchenware]"
2,12749.0,146544.45,7,401,22,6607.25,0.054863,22.179341,"[Others, Kitchenware]"
3,12820.0,11971.70,4,83,6,952.25,0.072289,12.572014,"[Others, Toys]"
4,12821.0,1374.10,1,4,0,0.00,0.000000,0.000000,[Others]

In [36]:
final_df.shape

(3910, 9)

In [37]:
final_df.columns

Index(['CUSTOMER_ID', 'TOTAL_SPENDING', 'FREQUENCY', 'TOTAL_QUANTITY',
       'NO_OF_ITEMS_RETURNED', 'RETURNED_AMOUNT', 'RETURN_RATIO',
       'RETURN_AMOUNT_RATIO', 'TOP_CATEGORY'],
      dtype='object')

In [38]:
final_df.to_excel("FINAL_PBL_DATASET_7.xlsx" , index = False)

In [39]:
final_df.isnull().sum()

CUSTOMER_ID             0
TOTAL_SPENDING          0
FREQUENCY               0
TOTAL_QUANTITY          0
NO_OF_ITEMS_RETURNED    0
RETURNED_AMOUNT         0
RETURN_RATIO            0
RETURN_AMOUNT_RATIO     0
TOP_CATEGORY            0
dtype: int64

In [40]:
final_df.describe()

,CUSTOMER_ID,TOTAL_SPENDING,FREQUENCY,TOTAL_QUANTITY,NO_OF_ITEMS_RETURNED,RETURNED_AMOUNT,RETURN_RATIO,RETURN_AMOUNT_RATIO
count,3910.000000,3.910000e+03,3910.000000,3910.000000,3910.000000,3910.000000,3910.000000,3910.000000
mean,15563.833760,3.470109e+04,4.759335,162.403836,11.342455,2244.043376,0.073013,24.426763
std,1575.254226,1.625790e+05,8.129996,387.154204,27.157879,8238.186341,0.084560,53.311773
min,12747.000000,2.535000e+01,1.000000,1.000000,0.000000,0.000000,0.000000,0.000000
25%,14211.250000,5.421650e+03,1.000000,30.000000,1.000000,122.525000,0.027778,5.224083
50%,15572.500000,1.449695e+04,2.000000,74.000000,5.000000,773.500000,0.060716,13.072520
75%,16912.750000,3.396673e+04,5.000000,180.000000,13.000000,2340.975000,0.091305,23.542212
max,18287.000000,7.686481e+06,208.000000,13958.000000,965.000000,325313.950000,1.000000,1140.333333

In [41]:
final_df.columns

Index(['CUSTOMER_ID', 'TOTAL_SPENDING', 'FREQUENCY', 'TOTAL_QUANTITY',
       'NO_OF_ITEMS_RETURNED', 'RETURNED_AMOUNT', 'RETURN_RATIO',
       'RETURN_AMOUNT_RATIO', 'TOP_CATEGORY'],
      dtype='object')