In [1]:
import pandas as pd
import numpy as np

In [2]:
df = pd.read_csv("PBL_DATA_SET_7.csv")

In [3]:
# df.to_excel("INITAL_DATA_SET_7.xlsx", index = False)

In [4]:
df.head()

,CUSTOMER_ID,INVOICE_NO,STOCK_CODE,QUANTITY,INVOICE_DATE,UNIT_PRICE,PRODUCT_CATEGORY,ITEM_RETURNED,NO_OF_ITEMS_RETURNED
0,17850.0,NaN,85123A,2,2010-12-01 08:26:00,-165.75,Others,N,0
1,17850.0,536365,71053,8,NaN,220.35,Others,NO,0
2,-17850.0,NaN,84406B,4,2010-12-01 08:26:00,178.75,Kitchenware,No,0
3,17850.0,536365,84029G,2,2010-12-01 08:26:00,220.35,Others,N,0
4,17850.0,536365,84029E,1,2010-12-01 08:26:00,220.35,Others,No,0

In [5]:
df.shape

(495478, 9)

In [6]:
df.columns

Index(['CUSTOMER_ID', 'INVOICE_NO', 'STOCK_CODE', 'QUANTITY', 'INVOICE_DATE',
       'UNIT_PRICE', 'PRODUCT_CATEGORY', 'ITEM_RETURNED',
       'NO_OF_ITEMS_RETURNED'],
      dtype='object')

In [7]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 495478 entries, 0 to 495477
Data columns (total 9 columns):
 #   Column                Non-Null Count   Dtype
---  ------                --------------   -----
 0   CUSTOMER_ID           337792 non-null  float64
 1   INVOICE_NO            448631 non-null  object
 2   STOCK_CODE            470224 non-null  object
 3   QUANTITY              495478 non-null  int64
 4   INVOICE_DATE          448239 non-null  object
 5   UNIT_PRICE            449081 non-null  float64
 6   PRODUCT_CATEGORY      457934 non-null  object
 7   ITEM_RETURNED         495478 non-null  object
 8   NO_OF_ITEMS_RETURNED  495478 non-null  int64
dtypes: float64(2), int64(2), object(5)
memory usage: 34.0+ MB

In [8]:
df.describe()

         CUSTOMER_ID       QUANTITY    UNIT_PRICE  NO_OF_ITEMS_RETURNED
count  337792.000000  495478.000000  4.490810e+05         495478.000000
mean    13426.081136       2.502024  2.345314e+02              0.334073
std      8001.156870       2.184020  6.678495e+03              1.122730
min    -18287.000000      -1.000000 -7.190339e+05              0.000000
25%     13988.000000       1.000000  5.395000e+01              0.000000
50%     15311.000000       2.000000  1.098500e+02              0.000000
75%     16859.000000       3.000000  2.437500e+02              0.000000
max     18287.000000      11.000000  2.533050e+06             15.000000

In [9]:
df.isnull().sum()

CUSTOMER_ID             157686
INVOICE_NO               46847
STOCK_CODE               25254
QUANTITY                     0
INVOICE_DATE             47239
UNIT_PRICE               46397
PRODUCT_CATEGORY         37544
ITEM_RETURNED                0
NO_OF_ITEMS_RETURNED         0
dtype: int64

In [10]:
(df["CUSTOMER_ID"].isnull().mean()) * 100

np.float64(31.825025530901474)

In [11]:
df = df.dropna(subset=["CUSTOMER_ID"])

In [12]:
df.head()

,CUSTOMER_ID,INVOICE_NO,STOCK_CODE,QUANTITY,INVOICE_DATE,UNIT_PRICE,PRODUCT_CATEGORY,ITEM_RETURNED,NO_OF_ITEMS_RETURNED
0,17850.0,NaN,85123A,2,2010-12-01 08:26:00,-165.75,Others,N,0
1,17850.0,536365,71053,8,NaN,220.35,Others,NO,0
2,-17850.0,NaN,84406B,4,2010-12-01 08:26:00,178.75,Kitchenware,No,0
3,17850.0,536365,84029G,2,2010-12-01 08:26:00,220.35,Others,N,0
4,17850.0,536365,84029E,1,2010-12-01 08:26:00,220.35,Others,No,0

In [13]:
df["STOCK_CODE"] = df["STOCK_CODE"].fillna("UNKNOWN")
df.head()

,CUSTOMER_ID,INVOICE_NO,STOCK_CODE,QUANTITY,INVOICE_DATE,UNIT_PRICE,PRODUCT_CATEGORY,ITEM_RETURNED,NO_OF_ITEMS_RETURNED
0,17850.0,NaN,85123A,2,2010-12-01 08:26:00,-165.75,Others,N,0
1,17850.0,536365,71053,8,NaN,220.35,Others,NO,0
2,-17850.0,NaN,84406B,4,2010-12-01 08:26:00,178.75,Kitchenware,No,0
3,17850.0,536365,84029G,2,2010-12-01 08:26:00,220.35,Others,N,0
4,17850.0,536365,84029E,1,2010-12-01 08:26:00,220.35,Others,No,0

In [14]:
df["UNIT_PRICE"].isnull().sum()

np.int64(31543)

In [ ]:
df = df.dropna(subset = ["INVOICE_NO", "INVOICE_DATE"], inplace = True)

In [ ]:
# df  = df.dropna("INVOICE_NO")
# df = df.dropna("INVOICE_DATE")

In [19]:
df["PRODUCT_CATEGORY"] = df["PRODUCT_CATEGORY"].fillna("Others")
df.head()

,CUSTOMER_ID,INVOICE_NO,STOCK_CODE,QUANTITY,INVOICE_DATE,UNIT_PRICE,PRODUCT_CATEGORY,ITEM_RETURNED,NO_OF_ITEMS_RETURNED
3,17850.0,536365,84029G,2,2010-12-01 08:26:00,220.35,Others,N,0
4,17850.0,536365,84029E,1,2010-12-01 08:26:00,220.35,Others,No,0
5,17850.0,536365,22752,1,2010-12-01 08:26:00,-497.25,Others,No,0
7,17850.0,536366,22633,4,2010-12-01 08:28:00,120.25,Others,No,0
8,17850.0,536366,22632,2,2010-12-01 08:28:00,120.25,Others,N,0

In [20]:
df.isnull().sum()

CUSTOMER_ID             0
INVOICE_NO              0
STOCK_CODE              0
QUANTITY                0
INVOICE_DATE            0
UNIT_PRICE              0
PRODUCT_CATEGORY        0
ITEM_RETURNED           0
NO_OF_ITEMS_RETURNED    0
dtype: int64

In [21]:
df[["CUSTOMER_ID","UNIT_PRICE","QUANTITY"]] = df[["CUSTOMER_ID","UNIT_PRICE","QUANTITY"]].abs()

In [22]:
df.head()

,CUSTOMER_ID,INVOICE_NO,STOCK_CODE,QUANTITY,INVOICE_DATE,UNIT_PRICE,PRODUCT_CATEGORY,ITEM_RETURNED,NO_OF_ITEMS_RETURNED
3,17850.0,536365,84029G,2,2010-12-01 08:26:00,220.35,Others,N,0
4,17850.0,536365,84029E,1,2010-12-01 08:26:00,220.35,Others,No,0
5,17850.0,536365,22752,1,2010-12-01 08:26:00,497.25,Others,No,0
7,17850.0,536366,22633,4,2010-12-01 08:28:00,120.25,Others,No,0
8,17850.0,536366,22632,2,2010-12-01 08:28:00,120.25,Others,N,0

In [23]:
df["ITEM_RETURNED"].value_counts()

ITEM_RETURNED
N      75684
No     75551
NO     74793
YES     8433
Y       8199
Yes     8192
Name: count, dtype: int64

In [24]:
df["ITEM_RETURNED"] = df["ITEM_RETURNED"].replace({"N" : "NO" , "No" : "NO" , "Y" : "YES" ,"Yes" : "YES"})

In [25]:
df["ITEM_RETURNED"].value_counts()

ITEM_RETURNED
NO     226028
YES     24824
Name: count, dtype: int64

In [26]:
df.head()

,CUSTOMER_ID,INVOICE_NO,STOCK_CODE,QUANTITY,INVOICE_DATE,UNIT_PRICE,PRODUCT_CATEGORY,ITEM_RETURNED,NO_OF_ITEMS_RETURNED
3,17850.0,536365,84029G,2,2010-12-01 08:26:00,220.35,Others,NO,0
4,17850.0,536365,84029E,1,2010-12-01 08:26:00,220.35,Others,NO,0
5,17850.0,536365,22752,1,2010-12-01 08:26:00,497.25,Others,NO,0
7,17850.0,536366,22633,4,2010-12-01 08:28:00,120.25,Others,NO,0
8,17850.0,536366,22632,2,2010-12-01 08:28:00,120.25,Others,NO,0

In [27]:
df[df["ITEM_RETURNED"]=="YES"].nunique()

CUSTOMER_ID              3211
INVOICE_NO              10420
STOCK_CODE               2796
QUANTITY                   11
INVOICE_DATE            10036
UNIT_PRICE                214
PRODUCT_CATEGORY            6
ITEM_RETURNED               1
NO_OF_ITEMS_RETURNED       15
dtype: int64

In [28]:
df1 = df[df["NO_OF_ITEMS_RETURNED"] <= df["QUANTITY"]]

In [29]:
df1.head()

,CUSTOMER_ID,INVOICE_NO,STOCK_CODE,QUANTITY,INVOICE_DATE,UNIT_PRICE,PRODUCT_CATEGORY,ITEM_RETURNED,NO_OF_ITEMS_RETURNED
3,17850.0,536365,84029G,2,2010-12-01 08:26:00,220.35,Others,NO,0
4,17850.0,536365,84029E,1,2010-12-01 08:26:00,220.35,Others,NO,0
5,17850.0,536365,22752,1,2010-12-01 08:26:00,497.25,Others,NO,0
7,17850.0,536366,22633,4,2010-12-01 08:28:00,120.25,Others,NO,0
8,17850.0,536366,22632,2,2010-12-01 08:28:00,120.25,Others,NO,0

In [30]:
df1.shape

(244495, 9)

In [31]:
df.shape

(250852, 9)

In [32]:
df2 = df1[~(
    (df1["ITEM_RETURNED"].str.upper().isin(["NO", "N"])) &
    (df1["NO_OF_ITEMS_RETURNED"] > 0)
)]

In [35]:
df2.shape

(238903, 9)

In [36]:
df2.head(100)

,CUSTOMER_ID,INVOICE_NO,STOCK_CODE,QUANTITY,INVOICE_DATE,UNIT_PRICE,PRODUCT_CATEGORY,ITEM_RETURNED,NO_OF_ITEMS_RETURNED
3,17850.0,536365,84029G,2,2010-12-01 08:26:00,220.35,Others,NO,0
4,17850.0,536365,84029E,1,2010-12-01 08:26:00,220.35,Others,NO,0
5,17850.0,536365,22752,1,2010-12-01 08:26:00,497.25,Others,NO,0
7,17850.0,536366,22633,4,2010-12-01 08:28:00,120.25,Others,NO,0
8,17850.0,536366,22632,2,2010-12-01 08:28:00,120.25,Others,NO,0
...,...,...,...,...,...,...,...,...,...
156,16029.0,536386,85099C,2,2010-12-01 09:57:00,107.25,Others,NO,0
157,16029.0,536386,85099B,3,2010-12-01 09:57:00,107.25,Others,NO,0
160,16029.0,536387,22779,2,2010-12-01 09:58:00,219.05,Others,NO,0
161,16029.0,536387,22466,2,2010-12-01 09:58:00,94.25,Others,NO,0
162,16029.0,536387,21731,2,2010-12-01 09:58:00,81.25,Others,NO,0

In [ ]:
# df2.to_excel("FINAL_PBL_DATA_SET_7.xlsx")

In [ ]:
# df2.to_csv("FINAL_PBL_DATA_SET_7.csv", index = False)