In [12]:
import pandas as pd
import numpy as np

In [13]:
df = pd.read_excel("updated_dataset.xlsx")

In [14]:
df.head(2)

,Unnamed: 0,CUSTOMER_ID,INVOICE_NO,STOCK_CODE,QUANTITY,INVOICE_DATE,UNIT_PRICE,PRODUCT_CATEGORY,ITEM_RETURNED,NO_OF_ITEMS_RETURNED
0,3,17850,536365,84029G,2,2010-12-01 08:26:00,220.35,Sports,NO,0
1,4,17850,536365,84029E,1,2010-12-01 08:26:00,220.35,gifts,NO,0

In [15]:
df.columns

Index(['Unnamed: 0', 'CUSTOMER_ID', 'INVOICE_NO', 'STOCK_CODE', 'QUANTITY',
       'INVOICE_DATE', 'UNIT_PRICE', 'PRODUCT_CATEGORY', 'ITEM_RETURNED',
       'NO_OF_ITEMS_RETURNED'],
      dtype='object')

In [16]:
df.drop(columns = "Unnamed: 0" , inplace = True)

In [17]:
df.head(2)

,CUSTOMER_ID,INVOICE_NO,STOCK_CODE,QUANTITY,INVOICE_DATE,UNIT_PRICE,PRODUCT_CATEGORY,ITEM_RETURNED,NO_OF_ITEMS_RETURNED
0,17850,536365,84029G,2,2010-12-01 08:26:00,220.35,Sports,NO,0
1,17850,536365,84029E,1,2010-12-01 08:26:00,220.35,gifts,NO,0

In [18]:
df.shape

(238903, 9)

In [19]:
df.columns

Index(['CUSTOMER_ID', 'INVOICE_NO', 'STOCK_CODE', 'QUANTITY', 'INVOICE_DATE',
       'UNIT_PRICE', 'PRODUCT_CATEGORY', 'ITEM_RETURNED',
       'NO_OF_ITEMS_RETURNED'],
      dtype='object')

In [20]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 238903 entries, 0 to 238902
Data columns (total 9 columns):
 #   Column                Non-Null Count   Dtype
---  ------                --------------   -----
 0   CUSTOMER_ID           238903 non-null  int64
 1   INVOICE_NO            238903 non-null  object
 2   STOCK_CODE            238903 non-null  object
 3   QUANTITY              238903 non-null  int64
 4   INVOICE_DATE          238903 non-null  object
 5   UNIT_PRICE            238903 non-null  float64
 6   PRODUCT_CATEGORY      238903 non-null  object
 7   ITEM_RETURNED         238903 non-null  object
 8   NO_OF_ITEMS_RETURNED  238903 non-null  int64
dtypes: float64(1), int64(3), object(5)
memory usage: 16.4+ MB

In [21]:
df.describe()

         CUSTOMER_ID       QUANTITY    UNIT_PRICE  NO_OF_ITEMS_RETURNED
count  238903.000000  238903.000000  2.389030e+05         238903.000000
mean    15545.247000       2.657978  2.131512e+02              0.185636
std      1595.265674       2.159896  5.395972e+03              0.718083
min     12747.000000       1.000000  0.000000e+00              0.000000
25%     14193.000000       1.000000  8.125000e+01              0.000000
50%     15513.000000       2.000000  1.267500e+02              0.000000
75%     16931.000000       3.000000  2.437500e+02              0.000000
max     18287.000000      11.000000  2.533050e+06             11.000000

In [22]:
df.isnull().sum()

CUSTOMER_ID             0
INVOICE_NO              0
STOCK_CODE              0
QUANTITY                0
INVOICE_DATE            0
UNIT_PRICE              0
PRODUCT_CATEGORY        0
ITEM_RETURNED           0
NO_OF_ITEMS_RETURNED    0
dtype: int64

In [23]:
(df["CUSTOMER_ID"].isnull().mean()) * 100

np.float64(0.0)

In [87]:
df["STOCK_CODE"] = df["STOCK_CODE"].fillna("UNKNOWN")
df.head()

,CUSTOMER_ID,INVOICE_NO,STOCK_CODE,QUANTITY,INVOICE_DATE,UNIT_PRICE,PRODUCT_CATEGORY,ITEM_RETURNED,NO_OF_ITEMS_RETURNED
0,17850,536365,84029G,2,2010-12-01 08:26:00,220.35,Sports,NO,0
1,17850,536365,84029E,1,2010-12-01 08:26:00,220.35,gifts,NO,0
2,17850,536365,22752,1,2010-12-01 08:26:00,497.25,gifts,NO,0
3,17850,536366,22633,4,2010-12-01 08:28:00,120.25,Sports,NO,0
4,17850,536366,22632,2,2010-12-01 08:28:00,120.25,gifts,NO,0

In [24]:
df["UNIT_PRICE"].isnull().sum()

np.int64(0)

In [25]:
df["PRODUCT_CATEGORY"] = df["PRODUCT_CATEGORY"].fillna("Others")
df.head()

,CUSTOMER_ID,INVOICE_NO,STOCK_CODE,QUANTITY,INVOICE_DATE,UNIT_PRICE,PRODUCT_CATEGORY,ITEM_RETURNED,NO_OF_ITEMS_RETURNED
0,17850,536365,84029G,2,2010-12-01 08:26:00,220.35,Sports,NO,0
1,17850,536365,84029E,1,2010-12-01 08:26:00,220.35,gifts,NO,0
2,17850,536365,22752,1,2010-12-01 08:26:00,497.25,gifts,NO,0
3,17850,536366,22633,4,2010-12-01 08:28:00,120.25,Sports,NO,0
4,17850,536366,22632,2,2010-12-01 08:28:00,120.25,gifts,NO,0

In [26]:
df.isnull().sum()

CUSTOMER_ID             0
INVOICE_NO              0
STOCK_CODE              0
QUANTITY                0
INVOICE_DATE            0
UNIT_PRICE              0
PRODUCT_CATEGORY        0
ITEM_RETURNED           0
NO_OF_ITEMS_RETURNED    0
dtype: int64

In [27]:
df[["CUSTOMER_ID","UNIT_PRICE","QUANTITY"]] = df[["CUSTOMER_ID","UNIT_PRICE","QUANTITY"]].abs()

In [28]:
df.head()

,CUSTOMER_ID,INVOICE_NO,STOCK_CODE,QUANTITY,INVOICE_DATE,UNIT_PRICE,PRODUCT_CATEGORY,ITEM_RETURNED,NO_OF_ITEMS_RETURNED
0,17850,536365,84029G,2,2010-12-01 08:26:00,220.35,Sports,NO,0
1,17850,536365,84029E,1,2010-12-01 08:26:00,220.35,gifts,NO,0
2,17850,536365,22752,1,2010-12-01 08:26:00,497.25,gifts,NO,0
3,17850,536366,22633,4,2010-12-01 08:28:00,120.25,Sports,NO,0
4,17850,536366,22632,2,2010-12-01 08:28:00,120.25,gifts,NO,0

In [29]:
df["ITEM_RETURNED"].value_counts()

ITEM_RETURNED
NO     214729
YES     24174
Name: count, dtype: int64

In [30]:
df["ITEM_RETURNED"] = df["ITEM_RETURNED"].replace({"N" : "NO" , "No" : "NO" , "Y" : "YES" ,"Yes" : "YES"})

In [31]:
df["ITEM_RETURNED"].value_counts()

ITEM_RETURNED
NO     214729
YES     24174
Name: count, dtype: int64

In [32]:
df.head()

,CUSTOMER_ID,INVOICE_NO,STOCK_CODE,QUANTITY,INVOICE_DATE,UNIT_PRICE,PRODUCT_CATEGORY,ITEM_RETURNED,NO_OF_ITEMS_RETURNED
0,17850,536365,84029G,2,2010-12-01 08:26:00,220.35,Sports,NO,0
1,17850,536365,84029E,1,2010-12-01 08:26:00,220.35,gifts,NO,0
2,17850,536365,22752,1,2010-12-01 08:26:00,497.25,gifts,NO,0
3,17850,536366,22633,4,2010-12-01 08:28:00,120.25,Sports,NO,0
4,17850,536366,22632,2,2010-12-01 08:28:00,120.25,gifts,NO,0

In [33]:
df[df["ITEM_RETURNED"]=="YES"].nunique()

CUSTOMER_ID              3197
INVOICE_NO              10304
STOCK_CODE               2776
QUANTITY                   11
INVOICE_DATE             9927
UNIT_PRICE                213
PRODUCT_CATEGORY           10
ITEM_RETURNED               1
NO_OF_ITEMS_RETURNED       11
dtype: int64

In [34]:
df1 = df[df["NO_OF_ITEMS_RETURNED"] <= df["QUANTITY"]]

In [35]:
df1.head()

,CUSTOMER_ID,INVOICE_NO,STOCK_CODE,QUANTITY,INVOICE_DATE,UNIT_PRICE,PRODUCT_CATEGORY,ITEM_RETURNED,NO_OF_ITEMS_RETURNED
0,17850,536365,84029G,2,2010-12-01 08:26:00,220.35,Sports,NO,0
1,17850,536365,84029E,1,2010-12-01 08:26:00,220.35,gifts,NO,0
2,17850,536365,22752,1,2010-12-01 08:26:00,497.25,gifts,NO,0
3,17850,536366,22633,4,2010-12-01 08:28:00,120.25,Sports,NO,0
4,17850,536366,22632,2,2010-12-01 08:28:00,120.25,gifts,NO,0

In [36]:
df1.shape

(238903, 9)

In [37]:
df.shape

(238903, 9)

In [38]:
df2 = df1[~(
    (df1["ITEM_RETURNED"].str.upper().isin(["NO", "N"])) &
    (df1["NO_OF_ITEMS_RETURNED"] > 0)
)]

In [39]:
df2.shape

(238903, 9)

In [41]:
df2.head()

,CUSTOMER_ID,INVOICE_NO,STOCK_CODE,QUANTITY,INVOICE_DATE,UNIT_PRICE,PRODUCT_CATEGORY,ITEM_RETURNED,NO_OF_ITEMS_RETURNED
0,17850,536365,84029G,2,2010-12-01 08:26:00,220.35,Sports,NO,0
1,17850,536365,84029E,1,2010-12-01 08:26:00,220.35,gifts,NO,0
2,17850,536365,22752,1,2010-12-01 08:26:00,497.25,gifts,NO,0
3,17850,536366,22633,4,2010-12-01 08:28:00,120.25,Sports,NO,0
4,17850,536366,22632,2,2010-12-01 08:28:00,120.25,gifts,NO,0

In [42]:
df2.to_csv("FINAL_PBL_DATA_SET_7.csv", index = False)

In [43]:
df2.shape

(238903, 9)