In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [3]:
df = pd.read_csv("FINAL_PBL_DATA_SET_7.csv" )

In [4]:
df_t = pd.read_excel("customer_top_category.xlsx")

In [89]:
avg_pur_gap = pd.read_csv("avg.purchace_gap.csv")

In [5]:
df_t.head()

   CustomerID TopCategory
0       12747      Sports
1       12748  Stationery
2       12749      Beauty
3       12820      Sports
4       12821      Beauty

In [6]:
df_t = df_t.rename(columns={"CustomerID": "CUSTOMER_ID"})

In [7]:
df.head()

,CUSTOMER_ID,INVOICE_NO,STOCK_CODE,QUANTITY,INVOICE_DATE,UNIT_PRICE,PRODUCT_CATEGORY,ITEM_RETURNED,NO_OF_ITEMS_RETURNED
0,17850,536365,84029G,2,2010-12-01 08:26:00,220.35,Sports,NO,0
1,17850,536365,84029E,1,2010-12-01 08:26:00,220.35,gifts,NO,0
2,17850,536365,22752,1,2010-12-01 08:26:00,497.25,gifts,NO,0
3,17850,536366,22633,4,2010-12-01 08:28:00,120.25,Sports,NO,0
4,17850,536366,22632,2,2010-12-01 08:28:00,120.25,gifts,NO,0

In [8]:
df.shape

(238903, 9)

In [9]:
df["SPENDING"] = df["QUANTITY"]*df["UNIT_PRICE"]

In [10]:
df["Returned_Amount"] = df["UNIT_PRICE"]*df["NO_OF_ITEMS_RETURNED"]

In [11]:
df.head()

,CUSTOMER_ID,INVOICE_NO,STOCK_CODE,QUANTITY,INVOICE_DATE,UNIT_PRICE,PRODUCT_CATEGORY,ITEM_RETURNED,NO_OF_ITEMS_RETURNED,SPENDING,Returned_Amount
0,17850,536365,84029G,2,2010-12-01 08:26:00,220.35,Sports,NO,0,440.70,0.0
1,17850,536365,84029E,1,2010-12-01 08:26:00,220.35,gifts,NO,0,220.35,0.0
2,17850,536365,22752,1,2010-12-01 08:26:00,497.25,gifts,NO,0,497.25,0.0
3,17850,536366,22633,4,2010-12-01 08:28:00,120.25,Sports,NO,0,481.00,0.0
4,17850,536366,22632,2,2010-12-01 08:28:00,120.25,gifts,NO,0,240.50,0.0

In [12]:
df["CUSTOMER_ID"].nunique()

3910

In [13]:
df_1 = df.groupby("CUSTOMER_ID")["SPENDING"].sum()

In [14]:
df1 = pd.DataFrame(df_1)

In [15]:
df1.head()

               SPENDING
CUSTOMER_ID
12747          50694.15
12748        1514026.80
12749         146544.45
12820          11971.70
12821           1374.10

In [16]:
df_2 = df.groupby("CUSTOMER_ID")["INVOICE_NO"].nunique()

In [17]:
df["TotalPrice"] = df["QUANTITY"] * df["UNIT_PRICE"]

In [18]:
df.head()

,CUSTOMER_ID,INVOICE_NO,STOCK_CODE,QUANTITY,INVOICE_DATE,UNIT_PRICE,PRODUCT_CATEGORY,ITEM_RETURNED,NO_OF_ITEMS_RETURNED,SPENDING,Returned_Amount,TotalPrice
0,17850,536365,84029G,2,2010-12-01 08:26:00,220.35,Sports,NO,0,440.70,0.0,440.70
1,17850,536365,84029E,1,2010-12-01 08:26:00,220.35,gifts,NO,0,220.35,0.0,220.35
2,17850,536365,22752,1,2010-12-01 08:26:00,497.25,gifts,NO,0,497.25,0.0,497.25
3,17850,536366,22633,4,2010-12-01 08:28:00,120.25,Sports,NO,0,481.00,0.0,481.00
4,17850,536366,22632,2,2010-12-01 08:28:00,120.25,gifts,NO,0,240.50,0.0,240.50

In [20]:
df_3 = df.groupby("CUSTOMER_ID").agg({
    'SPENDING': 'sum',
    'INVOICE_NO': 'nunique',
    'QUANTITY': 'sum'
}).rename(columns={
    'TOTAL_PRICE': 'Total_Spending',
    'INVOICE_NO': 'FREQUENCY',
    'QUANTITY': 'TOTAL_QUANTITY'
}).reset_index()

In [21]:
df_3.head()

   CUSTOMER_ID    SPENDING  FREQUENCY  TOTAL_QUANTITY
0        12747    50694.15         11             191
1        12748  1514026.80        208            8221
2        12749   146544.45          7             401
3        12820    11971.70          4              83
4        12821     1374.10          1               4

In [53]:
df_4 = df.groupby('CUSTOMER_ID').agg({
    'QUANTITY': 'sum',
    'NO_OF_ITEMS_RETURNED': 'sum',
}).reset_index()

In [54]:
df_4.head()

   CUSTOMER_ID  QUANTITY  NO_OF_ITEMS_RETURNED
0        12747       191                    13
1        12748      8221                   534
2        12749       401                    22
3        12820        83                     6
4        12821         4                     0

In [55]:
df_4['Return_Ratio'] = (
    df_4['NO_OF_ITEMS_RETURNED'] /
    df_4['QUANTITY']
)

In [56]:
df_4.head()

   CUSTOMER_ID  QUANTITY  NO_OF_ITEMS_RETURNED  Return_Ratio
0        12747       191                    13      0.068063
1        12748      8221                   534      0.064956
2        12749       401                    22      0.054863
3        12820        83                     6      0.072289
4        12821         4                     0      0.000000

In [57]:
df_5 = df.groupby('CUSTOMER_ID')['PRODUCT_CATEGORY'].apply(list).reset_index()

df_5.head()

   CUSTOMER_ID                                   PRODUCT_CATEGORY
0        12747  [Groceries, Electronics, Beauty, Beauty, Stati...
1        12748  [gifts, Stationery, Stationery, Groceries, Bea...
2        12749  [Stationery, Electronics, Electronics, gifts, ...
3        12820  [Beauty, Stationery, Beauty, Electronics, Spor...
4        12821                            [Beauty, gifts, Beauty]

In [58]:
df_5 = df.groupby('CUSTOMER_ID')['PRODUCT_CATEGORY'] \
               .apply(lambda x: sorted(set(x))) \
               .reset_index()

df_5.head()

   CUSTOMER_ID                                   PRODUCT_CATEGORY
0        12747  [Beauty, Electronics, Groceries, Home Decor, S...
1        12748  [Beauty, Clothing, Electronics, Groceries, Hom...
2        12749  [Beauty, Electronics, Groceries, Kitchenware, ...
3        12820  [Beauty, Electronics, Home Decor, Sports, Stat...
4        12821                                    [Beauty, gifts]

In [59]:
df_top2 = df.groupby('CUSTOMER_ID')['PRODUCT_CATEGORY'] \
    .agg(lambda x: x.value_counts().idxmax()) \
    .reset_index()

df_top2.head()

   CUSTOMER_ID PRODUCT_CATEGORY
0        12747           Sports
1        12748       Stationery
2        12749           Beauty
3        12820           Sports
4        12821           Beauty

In [60]:
df_top2["PRODUCT_CATEGORY"].value_counts()

PRODUCT_CATEGORY
Sports         794
Beauty         789
gifts          743
Electronics    725
Stationery     710
Kitchenware     84
Home Decor      39
Toys            21
Groceries        4
Clothing         1
Name: count, dtype: int64

In [61]:
merged_df = pd.merge(df_3, df_4, on='CUSTOMER_ID', how='inner')
merged_df.head()

,CUSTOMER_ID,SPENDING,FREQUENCY,TOTAL_QUANTITY,QUANTITY,NO_OF_ITEMS_RETURNED,Return_Ratio
0,12747,50694.15,11,191,191,13,0.068063
1,12748,1514026.80,208,8221,8221,534,0.064956
2,12749,146544.45,7,401,401,22,0.054863
3,12820,11971.70,4,83,83,6,0.072289
4,12821,1374.10,1,4,4,0,0.000000

In [62]:
df_raw = pd.read_csv("FINAL_PBL_DATA_SET_7.csv")   

df_raw['INVOICE_DATE'] = pd.to_datetime(df_raw['INVOICE_DATE'])

last_purchase = df_raw.groupby('CUSTOMER_ID')['INVOICE_DATE'].max().reset_index()
last_purchase = last_purchase.rename(columns={'INVOICE_DATE': 'Last_Purchase_Date'})
reference_date = df_raw['INVOICE_DATE'].max() + pd.Timedelta(days=1)

last_purchase['Recency'] = (reference_date - last_purchase['Last_Purchase_Date']).dt.days

In [63]:
merged_df1 = pd.merge(merged_df,last_purchase,on='CUSTOMER_ID', how='inner')
merged_df1.head()

,CUSTOMER_ID,SPENDING,FREQUENCY,TOTAL_QUANTITY,QUANTITY,NO_OF_ITEMS_RETURNED,Return_Ratio,Last_Purchase_Date,Recency
0,12747,50694.15,11,191,191,13,0.068063,2011-12-07 14:34:00,2
1,12748,1514026.80,208,8221,8221,534,0.064956,2011-12-09 12:20:00,1
2,12749,146544.45,7,401,401,22,0.054863,2011-12-06 09:56:00,4
3,12820,11971.70,4,83,83,6,0.072289,2011-12-06 15:12:00,3
4,12821,1374.10,1,4,4,0,0.000000,2011-05-09 15:51:00,214

In [91]:
final_df1 = pd.merge(merged_df1,df_top2,on='CUSTOMER_ID', how='inner')
final_df1.head()

,CUSTOMER_ID,SPENDING,FREQUENCY,TOTAL_QUANTITY,QUANTITY,NO_OF_ITEMS_RETURNED,Return_Ratio,Last_Purchase_Date,Recency,PRODUCT_CATEGORY
0,12747,50694.15,11,191,191,13,0.068063,2011-12-07 14:34:00,2,Sports
1,12748,1514026.80,208,8221,8221,534,0.064956,2011-12-09 12:20:00,1,Stationery
2,12749,146544.45,7,401,401,22,0.054863,2011-12-06 09:56:00,4,Beauty
3,12820,11971.70,4,83,83,6,0.072289,2011-12-06 15:12:00,3,Sports
4,12821,1374.10,1,4,4,0,0.000000,2011-05-09 15:51:00,214,Beauty

In [92]:
final_df = pd.merge(final_df1,avg_pur_gap, on = "CUSTOMER_ID" , how = "inner")
final_df.head()

,CUSTOMER_ID,SPENDING,FREQUENCY,TOTAL_QUANTITY,QUANTITY,NO_OF_ITEMS_RETURNED,Return_Ratio,Last_Purchase_Date,Recency,PRODUCT_CATEGORY,AVG_PURCHASE_GAP
0,12747,50694.15,11,191,191,13,0.068063,2011-12-07 14:34:00,2,Sports,36.300000
1,12748,1514026.80,208,8221,8221,534,0.064956,2011-12-09 12:20:00,1,Stationery,1.382488
2,12749,146544.45,7,401,401,22,0.054863,2011-12-06 09:56:00,4,Beauty,29.428571
3,12820,11971.70,4,83,83,6,0.072289,2011-12-06 15:12:00,3,Sports,107.333333
4,12821,1374.10,1,4,4,0,0.000000,2011-05-09 15:51:00,214,Beauty,0.000000

In [93]:
final_df.drop(columns = "Last_Purchase_Date" , inplace = True)

In [94]:
df.head()

,CUSTOMER_ID,INVOICE_NO,STOCK_CODE,QUANTITY,INVOICE_DATE,UNIT_PRICE,PRODUCT_CATEGORY,ITEM_RETURNED,NO_OF_ITEMS_RETURNED,SPENDING,Returned_Amount,TotalPrice
0,17850,536365,84029G,2,2010-12-01 08:26:00,220.35,Sports,NO,0,440.70,0.0,440.70
1,17850,536365,84029E,1,2010-12-01 08:26:00,220.35,gifts,NO,0,220.35,0.0,220.35
2,17850,536365,22752,1,2010-12-01 08:26:00,497.25,gifts,NO,0,497.25,0.0,497.25
3,17850,536366,22633,4,2010-12-01 08:28:00,120.25,Sports,NO,0,481.00,0.0,481.00
4,17850,536366,22632,2,2010-12-01 08:28:00,120.25,gifts,NO,0,240.50,0.0,240.50

In [95]:
type(final_df)

pandas.core.frame.DataFrame

In [96]:
final_df = final_df.drop('QUANTITY', axis=1)

In [97]:
final_df.head()

,CUSTOMER_ID,SPENDING,FREQUENCY,TOTAL_QUANTITY,NO_OF_ITEMS_RETURNED,Return_Ratio,Recency,PRODUCT_CATEGORY,AVG_PURCHASE_GAP
0,12747,50694.15,11,191,13,0.068063,2,Sports,36.300000
1,12748,1514026.80,208,8221,534,0.064956,1,Stationery,1.382488
2,12749,146544.45,7,401,22,0.054863,4,Beauty,29.428571
3,12820,11971.70,4,83,6,0.072289,3,Sports,107.333333
4,12821,1374.10,1,4,0,0.000000,214,Beauty,0.000000

In [98]:
final_df = final_df.rename(columns={'SPENDING': 'TOTAL_SPENDING', "Return_Amaount_Ratio": "RETURN_AMOUNT_RATIO" ,  "Return_Ratio":"RETURN_RATIO","Returned_Amount":"RETURNED_AMOUNT", "PRODUCT_CATEGORY" : "TOP_CATEGORY"})

In [99]:
print(type(final_df))

<class 'pandas.core.frame.DataFrame'>

In [100]:
final_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3910 entries, 0 to 3909
Data columns (total 9 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   CUSTOMER_ID           3910 non-null   int64
 1   TOTAL_SPENDING        3910 non-null   float64
 2   FREQUENCY             3910 non-null   int64
 3   TOTAL_QUANTITY        3910 non-null   int64
 4   NO_OF_ITEMS_RETURNED  3910 non-null   int64
 5   RETURN_RATIO          3910 non-null   float64
 6   Recency               3910 non-null   int64
 7   TOP_CATEGORY          3910 non-null   object
 8   AVG_PURCHASE_GAP      3910 non-null   float64
dtypes: float64(3), int64(5), object(1)
memory usage: 275.1+ KB

In [101]:
type(final_df)

pandas.core.frame.DataFrame

In [102]:
final_df.head()

,CUSTOMER_ID,TOTAL_SPENDING,FREQUENCY,TOTAL_QUANTITY,NO_OF_ITEMS_RETURNED,RETURN_RATIO,Recency,TOP_CATEGORY,AVG_PURCHASE_GAP
0,12747,50694.15,11,191,13,0.068063,2,Sports,36.300000
1,12748,1514026.80,208,8221,534,0.064956,1,Stationery,1.382488
2,12749,146544.45,7,401,22,0.054863,4,Beauty,29.428571
3,12820,11971.70,4,83,6,0.072289,3,Sports,107.333333
4,12821,1374.10,1,4,0,0.000000,214,Beauty,0.000000

In [103]:
final_df.shape

(3910, 9)

In [104]:
final_df.columns

Index(['CUSTOMER_ID', 'TOTAL_SPENDING', 'FREQUENCY', 'TOTAL_QUANTITY',
       'NO_OF_ITEMS_RETURNED', 'RETURN_RATIO', 'Recency', 'TOP_CATEGORY',
       'AVG_PURCHASE_GAP'],
      dtype='object')

In [105]:
final_df.to_excel("step2_data_set.xlsx" , index = False)

In [106]:
final_df.to_csv("FINAL_PBL_DATASET_13.csv", index = False)

In [107]:
final_df.isnull().sum()

CUSTOMER_ID             0
TOTAL_SPENDING          0
FREQUENCY               0
TOTAL_QUANTITY          0
NO_OF_ITEMS_RETURNED    0
RETURN_RATIO            0
Recency                 0
TOP_CATEGORY            0
AVG_PURCHASE_GAP        0
dtype: int64

In [108]:
final_df.describe()

,CUSTOMER_ID,TOTAL_SPENDING,FREQUENCY,TOTAL_QUANTITY,NO_OF_ITEMS_RETURNED,RETURN_RATIO,Recency,AVG_PURCHASE_GAP
count,3910.000000,3.910000e+03,3910.000000,3910.000000,3910.000000,3910.000000,3910.000000,3910.000000
mean,15563.833760,3.470109e+04,4.759335,162.403836,11.342455,0.073013,91.787980,43.575848
std,1575.254226,1.625790e+05,8.129996,387.154204,27.157879,0.084560,99.881497,60.092386
min,12747.000000,2.535000e+01,1.000000,1.000000,0.000000,0.000000,1.000000,0.000000
25%,14211.250000,5.421650e+03,1.000000,30.000000,1.000000,0.027778,17.000000,0.000000
50%,15572.500000,1.449695e+04,2.000000,74.000000,5.000000,0.060716,50.000000,24.258333
75%,16912.750000,3.396672e+04,5.000000,180.000000,13.000000,0.091305,143.000000,59.800000
max,18287.000000,7.686481e+06,208.000000,13958.000000,965.000000,1.000000,374.000000,365.000000

In [109]:
final_df.columns

Index(['CUSTOMER_ID', 'TOTAL_SPENDING', 'FREQUENCY', 'TOTAL_QUANTITY',
       'NO_OF_ITEMS_RETURNED', 'RETURN_RATIO', 'Recency', 'TOP_CATEGORY',
       'AVG_PURCHASE_GAP'],
      dtype='object')

In [110]:
final_df.shape

(3910, 9)

In [84]:
final_df

,CUSTOMER_ID,TOTAL_SPENDING,FREQUENCY,TOTAL_QUANTITY,NO_OF_ITEMS_RETURNED,RETURN_RATIO,Recency,TOP_CATEGORY
0,12747,50694.15,11,191,13,0.068063,2,Sports
1,12748,1514026.80,208,8221,534,0.064956,1,Stationery
2,12749,146544.45,7,401,22,0.054863,4,Beauty
3,12820,11971.70,4,83,6,0.072289,3,Sports
4,12821,1374.10,1,4,0,0.000000,214,Beauty
...,...,...,...,...,...,...,...,...
3905,18280,4774.25,1,20,0,0.000000,278,gifts
3906,18281,2094.30,1,18,0,0.000000,181,Stationery
3907,18282,2579.20,3,13,2,0.153846,8,Kitchenware
3908,18283,132707.90,15,1266,74,0.058452,4,Stationery
3909,18287,11934.65,3,135,21,0.155556,43,Beauty